project:
  type: website

author: Mikael Vejdemo-Johansson

website:
  title: "tieknots.how"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - grammar.qmd
      - knownties.qmd
      - press.qmd

resources:
  - "ties.css"
  - "jquery-2.0.3.min.js"
  - "lrc_pngs/"
  - "data/"
  - "*.png"
  - "site.webmanifest"

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    include-in-header:
      text: |
        <link rel="icon" type="image/png" sizes="256x256" href="/favicon.png">
        <link rel="icon" type="image/png" sizes="128x128" href="/favicon@128px.png">
        <link rel="icon" type="image/png" sizes="48x48" href="/favicon@48px.png">
	<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
	<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
	<link rel="manifest" href="/site.webmanifest">
