project:
  type: website

author: Mikael Vejdemo-Johansson

website:
  title: "tieknots.how"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - grammar.qmd
      - knownties.qmd
      - press.qmd

resources:
  - "ties.css"
  - "jquery-2.0.3.min.js"
  - "lrc_pngs/"
  - "data/"

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    include-in-header:
      text: | <link rel="icon" sizes="256x256" href="https://tieknots.how/favicon.png">
            | <link rel="icon" sizes="128x128" href="https://tieknots.how/favicon@128px.png">
            | <link rel="icon" sizes="48x48" href="https://tieknots.how/favicon@48px.png">
